<?xml version="1.0"?>
<package format="2">
  <name>firo_simulator</name>
  <version>1.0.0</version>
  <description>FIRO simulator metapackage</description>
  <maintainer email="gabriel@gabrielb.dev">Gabriel Brzeziński</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>firo_gazebo</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
